### ISSUE TITLE
Readme Asset

### ISSUE THREAD

**Issue by camenduru** [camenduru/FluxMusic-jupyter#1]
https://github.com/user-attachments/assets/cc8c8b87-561f-4a83-a1b5-eaadbe24f2b0

**Comment by DrakenZA** [comment]
Legend. Thanks for fixing the code. I cant believe the dev released this repo totally broken. In his readme to talks about sample.py and giving it an arg for ckpts, yet the sample.py code had no reference to that arg, and was just all hardcoded paths. Like come on.

But as always, camenduru to the rescue :)
